Added error message if P is not installed
p-org/peasy-ide-vscode pull request #29
Opened 2023-08-10 22:48 UTC by suesther

**Summary:**
I added a capability to the extension so that if P is not installed, an error message shows up at the terminal and as a VSCode error message. The red error message in the terminal shows up when users press f5, run tests in VSCode, or press **Save**. 
<img width="398" alt="Screenshot 2023-08-10 at 2 48 38 PM" src="https://github.com/p-org/peasy-ide-vscode/assets/135176059/d2baff78-54ab-4610-98b1-58b5667fccc4">

<img width="511" alt="Screenshot 2023-08-10 at 3 42 27 PM" src="https://github.com/p-org/peasy-ide-vscode/assets/135176059/785b9bd0-7f7d-48b4-adc1-98006c071a74">

Also, I added a capability to Testing where I run 
`p compile` BEFORE I run
`p check`. This means that users don't need to manually compile a P project folder before running P test cases. 

**How I accomplished this: **
I check the local file system to make sure that the P executable is downloaded at ~/.dotnet/tools. Then, going off from this, I will output an error message in VSCode if it doesn't exist. I will also output an echo command in the Terminal that shows the user instructions how to download P and where to download to P. 

NOTE: I also added some folders in the Examples folder so that users can see the extension at work. This is for a demo I have next week.

2023-08-10 23:49 UTC, ankushdesai requested changes
Do not commit generate code and binaries.

2023-08-11 00:03 UTC, suesther commented
> Do not commit generate code and binaries.

I deleted the generateCode and binaries.

2023-08-11 01:11 UTC, ankushdesai approved these changes

2023-08-14 18:51 UTC, mchadalavada approved these changes

2023-08-14 18:55 UTC, merged